apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-music-deployment
  labels:
    app: front-music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-music

  template:
    metadata:
      name: front-music
      labels:
        app: front-music
    spec:
      containers:
        - image: front-stream-music
          name: front-music
          imagePullPolicy: Never
          resources: {}
          ports:
            - containerPort: 80
