apiVersion: v1
kind: Pod
metadata:
  name: front-music
spec:
  containers:
    - image: front-stream-music
      name: front-music
      imagePullPolicy: Never
      resources: {}
      ports:
        - containerPort: 80
