apiVersion: v1
kind: Service
metadata:
  name: front-music-service
  labels:
    run: front-music
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: front-music
  type: NodePort
